# Docker Image which is used as foundation to create
# a custom Docker Image with this Dockerfile
FROM node:lts-alpine
 
# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app

# Adding since serve requires it
# RUN apk add xclip xsel
RUN apk add \
  --no-cache \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
  xsel

# Copies package.json and package-lock.json to Docker environment
COPY package*.json ./
 
# Installs all node packages
RUN npm install

# Creates production build
RUN npm run build

# Downloads server 
RUN npm install -g serve

# Copies everything over to Docker environment
COPY . .
 
# Uses port which is used by the actual application
EXPOSE 3000

RUN ls -ls

# Finally runs the application
CMD [ "npm","run", "prod" ]