# Docker Image which is used as foundation to create
# a custom Docker Image with this Dockerfile
FROM node:lts-alpine AS builder
 
# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app

# Copies package.json and package-lock.json to Docker environment
COPY package*.json ./
 
# Installs all node packages
RUN npm install

# Downloads server 
RUN npm install -g serve

# Copies everything over to Docker environment
COPY . .

# Creates production build
RUN npm run build
 
# Uses port which is used by the actual application
EXPOSE 3000

RUN ls -ls

# Finally runs the application
CMD [ "npm","run", "prod" ]