version: '3'
services:
  frontend:
    container_name: frontend
    image: index.docker.io/nskaria/brain-frontend:latest
    depends_on:
      - backend
    ports:
      - '80:80'
      # - '80:1000'
      # - '443:1000'
    # volumes:
    #   - caddy_data:/data
    #   - caddy_config:/config
  backend:
    container_name: backend
    image: index.docker.io/nskaria/brain-backend:latest
  typesense:
    container_name: typesense
    image: typesense/typesense:0.21.0
    ports:
      - 8108:8108
    environment:
      - TYPESENSE_API_KEY=123
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    logging:
      driver: none
volumes:
  #   caddy_data:
  #     external: true
  #   caddy_config:
  typesense_data:
