version: '3'
services:
  frontend:
    container_name: frontend
    image: index.docker.io/nskaria/brain-frontend:latest
    depends_on:
      - backend
    ports:
      - '80:80'
      # - '80:1000'
      # - '443:1000'
    # volumes:
    #   - caddy_data:/data
    #   - caddy_config:/config
  backend:
    container_name: backend
    image: index.docker.io/nskaria/brain-backend:latest
# volumes:
#   caddy_data:
#     external: true
#   caddy_config:
