version: '3'
services:
  frontend:
    container_name: frontend
    image: index.docker.io/nskaria/brain-frontend:latest
    environment:
      - REACT_APP_HASURA=J2569eeva
      - HASURA=J2569eeva
    # depends_on:
    #   - backend
    ports:
      - '80:80'

  # backend:
  #   container_name: backend
  #   image: index.docker.io/nskaria/brain-backend:latest
