name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy-back:
    name: Build and Deploy Back-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nskaria/brain-backend
          dockerfile: backend/Dockerfile
          tag_with_ref: true
          tag_with_sha: true
          tags: latest

  build-and-deploy-front:
    name: Build and Deploy Front-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nskaria/brain-frontend
          dockerfile: frontend/Dockerfile
          build-args: FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}, FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}}, FIREBASE_DATABASE_URL=${{secrets.FIREBASE_DATABASE_URL}}, FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}}, FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}}, FIREBASE_MESSAGING_SENDER_ID=${{secrets.FIREBASE_MESSAGING_SENDER_ID}}, FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}, HASURA=${{secrets.HASURA}}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
